#!/bin/bash
cd ~/.burg-manager
wget http://www.sourceslist.eu/ccount/click.php?id=25
now=$(cat ~/.burg-manager/click.php?id=25|tr -d ".")
rm -rf ~/.burg-manager/click.php?id=25
installed=$(cat /usr/share/burg-manager/version|tr -d ".")
#installed=$(cat /usr/share/burg-manager/version)
if [ "$now" -gt "$installed" ] ; 
then
buc /usr/share/burg-manager/updateavaible.mc
fi
exit 0